// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOrsUSNELj2MfyxWPlgt4pB0gEGa2bVUo',
    appId: '1:251498802868:web:50185b2235dcb4b534b1e1',
    messagingSenderId: '251498802868',
    projectId: 'eos-clock-a6511',
    authDomain: 'eos-clock-a6511.firebaseapp.com',
    storageBucket: 'eos-clock-a6511.appspot.com',
    measurementId: 'G-T9KQWRFQDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-DgCrpALcc50yM7vyoiChkcTj6QFNFsw',
    appId: '1:251498802868:android:0a0c84553da590f234b1e1',
    messagingSenderId: '251498802868',
    projectId: 'eos-clock-a6511',
    storageBucket: 'eos-clock-a6511.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0rM77BKX3dObdT353Fp19W2cexx5e0E8',
    appId: '1:251498802868:ios:099c6b54690f869a34b1e1',
    messagingSenderId: '251498802868',
    projectId: 'eos-clock-a6511',
    storageBucket: 'eos-clock-a6511.appspot.com',
    iosClientId: '251498802868-dec29i574mat7fsojqkm67es7e032es8.apps.googleusercontent.com',
    iosBundleId: 'com.eos.eosChatting',
  );
}
