// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXRLBUWHp_pNJpPmt_aGG95kaioKOxHWk',
    appId: '1:621933466081:web:36b64c28a07d63f0fd82a0',
    messagingSenderId: '621933466081',
    projectId: 'eos-chatting-7cce8',
    authDomain: 'eos-chatting-7cce8.firebaseapp.com',
    storageBucket: 'eos-chatting-7cce8.appspot.com',
    measurementId: 'G-WENTSR3BCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm5k-_RwcfjDMJMm5zlQbcShSCrL6GXBA',
    appId: '1:621933466081:android:c74918d30a73c210fd82a0',
    messagingSenderId: '621933466081',
    projectId: 'eos-chatting-7cce8',
    storageBucket: 'eos-chatting-7cce8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChqtNhXidoW00FsjuqCPCiVEJdrtSDoQ0',
    appId: '1:621933466081:ios:7cbf2d425e151c8afd82a0',
    messagingSenderId: '621933466081',
    projectId: 'eos-chatting-7cce8',
    storageBucket: 'eos-chatting-7cce8.appspot.com',
    iosClientId: '621933466081-kjhkqv6smab6sm51lhuc5kjnqss2qq8h.apps.googleusercontent.com',
    iosBundleId: 'com.eos.eosChatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChqtNhXidoW00FsjuqCPCiVEJdrtSDoQ0',
    appId: '1:621933466081:ios:7cbf2d425e151c8afd82a0',
    messagingSenderId: '621933466081',
    projectId: 'eos-chatting-7cce8',
    storageBucket: 'eos-chatting-7cce8.appspot.com',
    iosClientId: '621933466081-kjhkqv6smab6sm51lhuc5kjnqss2qq8h.apps.googleusercontent.com',
    iosBundleId: 'com.eos.eosChatting',
  );
}
